listener 1883
allow_anonymous true

set_tcp_nodelay true          # выключает Nagle на всех сокетах брокера

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
